### ISSUE TITLE
Level generator improvements

### ISSUE THREAD

**Issue by iacopy** [RookieGameDevs/surviveler#15] opened 2017-02-12 13:43 UTC
- [ ] Update mesh when parameters are updated
- [ ] Parametrized random generation
- [ ] Doors creation
- [x] Floor creation
- [ ] Support for non-rect walls (pixels with specific color for non-rect walls)

**Comment by duploduplo** [comment] 2017-05-03 18:21
Closed: sounds like it's a duplicate of #13

**Closed as completed by duploduplo** 2017-05-03 18:21 UTC
Labels: enhancement
